// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include <iostream>
#include "catch.hpp"
#include "main.hpp"
// tests for exercise 1

TEST_CASE("Ex1 ", "[example]")
{
	int N = 10;
	int swapcnt;
	vector<int> numbers;
	fillvector(numbers, N);
	print(numbers);

	quicksort(numbers, 0, numbers.size() - 1);
	print(numbers);
	cout << "Swap cnt : " << swapcnt << endl;
	for (int i = 0; i < N - 1; i++)
		REQUIRE(numbers[i] <= numbers[i + 1]);
}

TEST_CASE("Ex2 ", "[example]")
{
	int N = 10;
	int swapcnt, pidx;
	vector<int> numbers;
	fillvector(numbers, N);
	print(numbers);

	pidx = partition(numbers, 0, 9);
	print(numbers);
	cout << "Returned Pivot index : " << pidx << endl;
	for (int i = 0; i < pidx; i++)
		REQUIRE(numbers[i] <= numbers[pidx]);
	for (int i = pidx; i < 10; i++)
		REQUIRE(numbers[i] >= numbers[pidx]);
}
